### ISSUE TITLE
Doesn't seem to run with Windows 10

### ISSUE THREAD

**Issue by Spork-Schivago** [w4kfu/unEXEPACK#1]
I am trying to unEXEPACK an EXEPACK 16-bit MS-DOS application in Windows 10 64-bit.   I've complied the program using MinGW, however, it fails and displays:

SizeFile = 1207A
read(): No error

It's having trouble with this line of code for some reason:
   if (read(fd, buf_load, st.st_size) != st.st_size)

Any suggestions on how to fix it?   Thanks!

**Comment by w4kfu** [comment]
Hello,

Any chance you share the ms-dos executable that triggers this problem?

thx

**Comment by w4kfu** [comment]
The problem came from the fact that the flag `O_BINARY` was not used for `open()`. It is mandatory on Windows, I have now fixed it in : https://github.com/w4kfu/unEXEPACK/commit/361be9c92f5437898812dce3096e717f6ff5045b.

Let me know if it is working.

**Comment by Spork-Schivago** [comment]
It does not display the read(): No Error message anymore.

While compiling, albeit a separate issue, I thought you'd like to know the following warning is displayed:

unpack.c: In function 'hex_dump':
unpack.c:346:13: warning: implicit declaration of function 'isalnum' [-Wimplicit-function-declaration]
         if (isalnum(c) == 0)

For my system (Windows 10 Enterprise, running MSYS using the MinGW compiler), this was fixed by including ctype.h at the end of the header #include's.

**EDIT:

There is a new issue now:

This is not a valid exepack executable

I believe it's because this is a very early implementation of EXEPACK (3.61, if I recall) and I am thinking it might not support skip_len.   I will patch the code and report back in the other open issue that mentions skip_len if that is the case.

Thanks!
