### ISSUE TITLE
Project rewritting

### ISSUE THREAD

**Issue by w4kfu** [w4kfu/unEXEPACK#2]
Project is 9 years old and need to be seriously cleaned up.

Also it could be a good idea to move it to a Python version.

**Comment by Spork-Schivago** [comment]
I personally love seeing the C source code.   If you decide to do the Python thing, maybe you'd consider cloning the repo and having a Python version and a C version?

Although the code does need some updating, C is still very much alive and being used.   For example, I have a 16-bit MS-DOS OS installed in a virtual machine, but use Windows 10.   I do work in MS-DOS and in Windows.   I can use Microsoft Quick C for the DOS environment, and MinGW for the Windows environment.   I haven't looked, but I don't think there's a Python for MS-DOS.   With some C code, I might have to change a few things to get it work with MS-DOS, but I am okay with that.

I realize not many people are probably running MS-DOS, but I also doubt many people have a need to unpack EXEPACKed files.   I would think that most people that have a need for this program would be working with a 16-bit application.   Maybe I am wrong and EXEPACK is still being used with modern Microsoft compilers.

**Comment by w4kfu** [comment]
Projet rewritten see https://github.com/w4kfu/unEXEPACK/commit/df3e32934dfe1ec066bfbbfd7575a715e9064df1
